### ISSUE TITLE
When trying to run the latest build of DashLoader alongside this mod, game craps itself and refuses to boot

### ISSUE THREAD

**Issue by Sunconure11** [Fuzss/puzzleslib-fabric#1] opened 2022-02-13 15:39 UTC
![Screenshot 2022-02-13 10 17 15](https://user-images.githubusercontent.com/5614902/153760766-802f3bc9-49dc-4942-bc33-8b9238cba9be.png)

Example of the error in question. If needed, I can give more info.

**Comment by Fuzss** [comment] 2022-02-13 16:39
Can't reproduce, I need your `latest.log` file for more info.

**Comment by Sunconure11** [comment] 2022-02-13 16:53
It... seemingly resolved itself.

**Comment by Fuzss** [comment] 2022-02-13 17:01
If you can still find the log from that launch we could find out what happened.

Pretty sure though this happened because of another mod, because Puzzles, well doesn't do anything at all. It only provides resources for other mods.

**Comment by Sunconure11** [comment] 2022-02-13 17:56
https://pastebin.com/9cu6kdUS

It came back

**Comment by Sunconure11** [comment] 2022-02-13 18:01
Removing Forge Config API stopped it.

**Comment by Fuzss** [comment] 2022-07-10 07:13
I haven't been able to find any correlation of this issues with either Puzzles Lib or Forge Config API Port, therefore closing now. If you can reproduce the issue with just the two mods of mine please open a new one here, as this repository will now be archived: https://github.com/Fuzss/puzzleslib

**Closed as completed by Fuzss** 2022-07-10 07:13 UTC
